version: '3.8'
services:

  web:
    build:
      context: .
    volumes:
      - .:/var/www

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    volumes:
      - db:/var/lib/postgresql/data:rw

volumes:
  db:
